# Generated by Django 5.1.3 on 2024-12-10 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProCoders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='explation',
            new_name='explanation',
        ),
        migrations.AlterField(
            model_name='information',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information', to='ProCoders.languages'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='ProCoders.languages'),
        ),
    ]
