# Generated by Django 5.1.3 on 2024-12-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProCoders', '0002_languages_rename_explation_quiz_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
