# Generated by Django 5.1.3 on 2024-12-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProCoders', '0003_languages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='language_images/'),
        ),
    ]
