# Generated by Django 5.1.3 on 2024-12-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProCoders', '0005_alter_languages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/Supports/Language/'),
        ),
    ]
