# Generated by Django 5.1.3 on 2024-12-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProCoders', '0008_alter_message_send_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/Supports/Information/'),
        ),
    ]
