# Generated by Django 5.1.3 on 2024-12-12 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProCoders', '0009_information_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='send_by',
            new_name='user',
        ),
    ]
