# Generated by Django 5.1.3 on 2024-12-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProCoders', '0010_rename_send_by_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='iframe_url',
            field=models.TextField(null=True),
        ),
    ]
